# Generated by Django 4.2.7 on 2023-11-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meal",
            old_name="mass",
            new_name="portion_size",
        ),
        migrations.AddField(
            model_name="nutritionhistory",
            name="blood_sugar_after",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nutritionhistory",
            name="blood_sugar_before",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
