# Generated by Django 4.2.7 on 2023-11-29 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0002_rename_mass_meal_portion_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="timestamp",
        ),
    ]
