# Generated by Django 4.2.7 on 2023-12-02 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_interaction", "0002_chat_diabetesanswer_remove_usermessage_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="answer_text",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="DiabetesAnswer",
        ),
    ]
